In [1]:
!pip install numpy

### Numpy -- play with array ( numbers )
### Pandas -- dataset
### Matplotlib -- Data visualization
### seaborn -- Data visualization
### Scipy -- Statistical analysis
### Sklearn -- Algorithm

# Numpy: package for Multidimesional array

In [2]:
import numpy as np

In [3]:
n = np.array((1,2,3))
print(n)

[1 2 3]


In [4]:
print(type(n))

<class 'numpy.ndarray'>


In [5]:
List=[[1,2,3],[4,5,6],[7,8,9]]
np.array(List)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,36,5) # shift+tab = help box

array([ 1,  6, 11, 16, 21, 26, 31])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
np.random.rand(3,5)

array([[0.99313972, 0.80059909, 0.03476452, 0.43221425, 0.99675817],
       [0.66668089, 0.77190039, 0.44398948, 0.3875432 , 0.29063072],
       [0.96270397, 0.42516836, 0.00716149, 0.88594621, 0.02264742]])

In [23]:
arr= np.random.randn(2,4)
arr

array([[-1.99554713, -0.51267912,  1.59146794,  0.5367547 ],
       [ 0.04850388, -0.06135405, -1.13526388,  1.34633604]])

In [24]:
np.random.randint(2,100)

66

In [25]:
np.random.randint(20,56,100)

array([48, 26, 47, 26, 24, 51, 42, 37, 21, 38, 51, 30, 44, 48, 40, 54, 52,
       27, 23, 53, 22, 34, 47, 25, 46, 42, 38, 49, 30, 41, 50, 23, 33, 21,
       36, 42, 52, 48, 53, 21, 33, 32, 25, 20, 29, 29, 20, 53, 24, 55, 30,
       21, 50, 51, 29, 43, 30, 27, 28, 37, 51, 23, 20, 21, 51, 20, 21, 42,
       49, 24, 51, 30, 53, 49, 32, 45, 37, 21, 25, 48, 48, 34, 54, 52, 49,
       36, 30, 32, 43, 49, 39, 27, 38, 44, 42, 27, 44, 48, 47, 49])

In [26]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
rand_array=np.random.randint(0,10,50)
rand_array

array([3, 7, 6, 3, 5, 4, 1, 8, 5, 7, 6, 0, 3, 2, 7, 5, 3, 6, 0, 1, 0, 8,
       3, 3, 2, 2, 8, 0, 3, 1, 6, 6, 7, 3, 0, 5, 9, 5, 9, 7, 7, 7, 3, 0,
       1, 0, 0, 3, 2, 3])

In [28]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [30]:
rand_array.max()

9

In [31]:
rand_array.argmax()

36

In [32]:
rand_array.min()

0

In [33]:
rand_array.argmin()

11

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,3)
a

array([[0.33704666, 0.816751  , 0.46389789],
       [0.67717235, 0.70930631, 0.66568114]])

In [37]:
a.T

array([[0.33704666, 0.67717235],
       [0.816751  , 0.70930631],
       [0.46389789, 0.66568114]])

In [38]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
sample_array[0]

10

In [40]:
sample_array[2:5]

array([12, 13, 14])

In [41]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [42]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

## Tow-Dimensional array

In [3]:
import numpy as np

In [4]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [5]:
sample_matrix[1,2]

21

In [6]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [7]:
sample_matrix[2]

array([56, 76, 24,  7])

In [8]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [9]:
sample_matrix[1,(1,2)]

array([23, 21])

## Selection techniques

In [10]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [12]:
np.exp(sample_array)#exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [13]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [14]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [15]:
np.max(sample_array)

19

In [16]:
np.min(sample_array)

1

In [17]:
np.argmax(sample_array)

18

In [18]:
np.argmin(sample_array)

0

In [19]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [20]:
np.std(sample_array)

5.477225575051661

In [21]:
np.var(sample_array)

30.0

In [22]:
np.mean(sample_array)

10.0

In [23]:
array=np.random.randn(3,4)
array

array([[ 0.14473662,  0.10323856, -0.33109714,  0.8024637 ],
       [ 1.46285239, -0.32581781, -0.99455869, -0.89268614],
       [ 0.22117427,  0.14258981,  1.07499245,  0.56575018]])

In [27]:
np.round(array,decimals=2)

array([[ 0.14,  0.1 , -0.33,  0.8 ],
       [ 1.46, -0.33, -0.99, -0.89],
       [ 0.22,  0.14,  1.07,  0.57]])

In [30]:
sports=np.array(['golf','cricket','football','cricket'])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

# Pandas

In [31]:
import pandas as pd
import numpy as np

## Pandas dataframe and indexing

In [34]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [35]:
sports1['football']

2

In [36]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [37]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [39]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.883828  0.067022  0.419912  0.184129  0.167947
B  0.704575  0.456456  0.522680  0.300664  0.799154
C  0.814345  0.368369  0.631977  0.699178  0.358521
D  0.529911  0.020169  0.622884  0.935788  0.056878
E  0.425133  0.619790  0.835122  0.934707  0.034672
F  0.247147  0.736879  0.118865  0.503791  0.136378
G  0.706013  0.872907  0.922564  0.446091  0.717338
H  0.147680  0.203786  0.152548  0.990484  0.346753

In [40]:
df1['Score1']

A    0.883828
B    0.704575
C    0.814345
D    0.529911
E    0.425133
F    0.247147
G    0.706013
H    0.147680
Name: Score1, dtype: float64

In [41]:
df1[['Score1','Score2']]

Score1    Score2
A  0.883828  0.067022
B  0.704575  0.456456
C  0.814345  0.368369
D  0.529911  0.020169
E  0.425133  0.619790
F  0.247147  0.736879
G  0.706013  0.872907
H  0.147680  0.203786

In [42]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.883828  0.067022  0.419912  0.184129  0.167947  0.950849
B  0.704575  0.456456  0.522680  0.300664  0.799154  1.161030
C  0.814345  0.368369  0.631977  0.699178  0.358521  1.182715
D  0.529911  0.020169  0.622884  0.935788  0.056878  0.550080
E  0.425133  0.619790  0.835122  0.934707  0.034672  1.044923
F  0.247147  0.736879  0.118865  0.503791  0.136378  0.984026
G  0.706013  0.872907  0.922564  0.446091  0.717338  1.578920
H  0.147680  0.203786  0.152548  0.990484  0.346753  0.351466

In [46]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [47]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [48]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [50]:
df=df.drop("ID",axis=1)

In [51]:
df

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [52]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
4  Lally     123